name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: yarn install

      - name: Tests
        run: yarn test:unit run --bail 1

      - name: Build
        run: yarn build

      - name: Organize files
        run: mv dist/* ./
